export const vaccinationCenterList = [
  {
    id: 1,
    name: "Hong Kah North Community Centre",
    dailyNurses: 10,
    address: "30 Bukit Batok Street 31",
    country: "Singapore 659440",
    operatingHours: "8am – 10pm",
    allocatedSlots: 100,
  },
  {
    id: 2,
    name: "Marine Parade Community Centre",
    dailyNurses: 15,
    address: "278 Marine Parade Rd",
    country: "Singapore 449282",
    operatingHours: "9am – 9pm",
    allocatedSlots: 80,
  },
  {
    id: 3,
    name: "Marsiling Community Centre",
    dailyNurses: 12,
    address: "100 AdmiraltyRd",
    country: "Singapore 739980",
    operatingHours: "10am – 10pm",
    allocatedSlots: 100,
  },
  {
    id: 4,
    name: "Nanyang Community Centre",
    dailyNurses: 10,
    address: "60 Jurong West Street 91",
    country: "Singapore 649040",
    operatingHours: "8am – 8pm",
    allocatedSlots: 90,
  },
  {
    id: 5,
    name: "Nee Soon East Community Centre",
    dailyNurses: 12,
    address: "1 Yishun Ave 9",
    country: "Singapore 768893",
    operatingHours: "8am – 10pm",
    allocatedSlots: 110,
  },
  {
    id: 6,
    name: "Pasir Ris Elias Community Centre",
    dailyNurses: 18,
    address: "93 Pasir Ris Drive 3",
    country: "Singapore 519498",
    operatingHours: "9am – 10pm",
    allocatedSlots: 100,
  },
  {
    id: 7,
    name: "Punggol 21 Community Centre",
    dailyNurses: 20,
    address: "80 Punggol Field",
    country: "Singapore 828815",
    operatingHours: "9am – 8pm",
    allocatedSlots: 50,
  },
  {
    id: 8,
    name: "Queenstown Community Centre",
    dailyNurses: 12,
    address: "365 Commonwealth Ave",
    country: "Singapore 149732",
    operatingHours: "8am – 10pm",
    allocatedSlots: 50,
  },
  {
    id: 9,
    name: "Raffles Medical Clinic Compass One",
    dailyNurses: 15,
    address: "1 Sengkang Square #04-09, Compass Mall One",
    country: "Singapore 545078",
    operatingHours: "8am – 10pm",
    allocatedSlots: 100,
  },
  {
    id: 10,
    name: "Raffles Medical Clinic Holland Village",
    dailyNurses: 10,
    address: "118 Holland Avenue #05-02/03/04",
    country: "Singapore 278997",
    operatingHours: "9am – 9pm",
    allocatedSlots: 80,
  },
  {
    id: 11,
    name: "SengKang Community Centre",
    dailyNurses: 12,
    address: "2 Sengkang Square, #01-01",
    country: "Singapore 545025",
    operatingHours: "10am – 10pm",
    allocatedSlots: 100,
  },
  {
    id: 12,
    name: "Tanjong Pagar Community Centre",
    dailyNurses: 10,
    address: "101 Cantonment Rd",
    country: "Singapore 089774",
    operatingHours: "8am – 10pm",
    allocatedSlots: 80,
  },
  {
    id: 13,
    name: "Teck Ghee Community Centre",
    dailyNurses: 8,
    address: "861 Ang Mo Kio Ave 10",
    country: "Singapore 569734",
    operatingHours: "9am – 10pm",
    allocatedSlots: 100,
  },
];
